# High-level consensus params
QUERY_ROUNDS = 10
NETWORK_SAMPLE_SIZE = 10
ALPHA_PARAM = 0.5
BETA_CONFIDENCE_PARAM = 10
BETA_CONSECUTIVE_PARAM = 10
MAX_PARENTS = 10
MAX_QUERY_ITERATIONS = 10

# Networking settings
CLIENT_SOCKET_TIMEOUT = 3  # seconds
QUERY_TIMEOUT = 10  # seconds
TIME_BETWEEN_QUERIES = 0.005  # seconds
DISCOVERY_STARTUP_DELAY = 3  # seconds
SYNC_GRAPH_DELAY = 8  # seconds
MAX_BROADCAST_PEERS = 10
NETWORK_LATENCY_MIN = 0.001 * 1000  # milliseconds
NETWORK_LATENCY_MAX = 1 * 1000  # milliseconds

# Testing settings
PEERS_COUNT = 10
RANDOM_TX_GENERATION = 0.05  # seconds
TX_GEN_RATE = 10
METRICS_DURATION = 100
TPS_BENCHMARK = 1000
INIT_SERVER_DELAY = 5
