# High-level consensus params
QUERY_ROUNDS = 10
NETWORK_SAMPLE_SIZE = 10
ALPHA_PARAM = 0.5
BETA_CONFIDENCE_PARAM = 10
BETA_CONSECUTIVE_PARAM = 10
MAX_PARENTS = 10
MAX_QUERY_ITERATIONS = 20

# Networking settings
QUERY_TIMEOUT = 3  # seconds
TIME_BETWEEN_QUERIES = 0.005  # seconds
DISCOVERY_STARTUP_DELAY = 3  # seconds
RANDOM_TX_GENERATION = 5  # seconds
NETWORK_LATENCY_MIN = 0.001 * 1000  # milliseconds
NETWORK_LATENCY_MAX = 1 * 1000  # milliseconds
